/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import Business.DB4OUtil.DB4OUtil;
import Business.Ecosystem;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author victor
 */
public class MainJFrame extends JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        setUndecorated(true);
        initComponents();
        setSize(850, 600);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setResizable(false);
        setTitle("City Typhoon Safety System");
        DB4OUtil dB4OUtil = DB4OUtil.getInstance();
        Ecosystem system = dB4OUtil.retrieveSystem();
        Ecosystem.setEcosystem(system);
        initLoginScreen();
        setLocationRelativeTo(null);
    }

    public static void setSize(JFrame frame, int width, int height) {
        //一定要在JFrame显示之前调用
        frame.pack();

        //在默认的setResizable(true); 情况下,titleDefaultHeight = 27,但如果 setResizable(false); titleDefaultHeight = 25
        int titleDefaultHeight = frame.isResizable() ? 27 : 25; //默认开发阶段使用windows 经典主题,标题栏高度= 27

        int containerHeight = frame.getContentPane().getHeight();
        //System.out.println("containerHeight:" + containerHeight); //windows 经典主题或xp主题下 = 1
        //int rootPaneHeight = frame.getRootPane().getHeight(); //取得的高度和container的高度是一样的

        int frameHeight = frame.getHeight();
        //System.out.println("frameHeight:" + frameHeight); //windows经典主题下= 28, windows xp 主题下 = 33

        int titleHeight = frameHeight - containerHeight; //这里就可以得到当前标题栏的实际高度
        if (titleHeight > titleDefaultHeight) {
            int h = titleHeight - titleDefaultHeight; //得到当前使用的主题,标题栏 - 经典主题下的标题栏高度 = 差值
            frame.setSize(width, height + h); //最终确定窗口的高度
        } else {
            frame.setSize(width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(new java.awt.BorderLayout());

        mainWorkArea.setMaximumSize(new java.awt.Dimension(850, 600));
        mainWorkArea.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainWorkArea, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame mainJFrame = new MainJFrame();

                mainJFrame.setVisible(true);
                //                new LoginScreen();
                ;

            }
        });
    }

    private void initLoginScreen() {
        JPanel loginScreen = new Login(mainWorkArea);
        mainWorkArea.add(loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.first(mainWorkArea);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables
}
