/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Resident;

import Business.Employee.Employee;
import Business.Role.EachFoodRecord;
import Business.Utilities.Address;
import Business.WorkQueue.CarInsuranceRequest;
import Business.WorkQueue.ElectricityRequest;
import Business.WorkQueue.FoodRequest;
import Business.WorkQueue.HospitalRequest;
import Business.WorkQueue.HouseInsuranceRequest;
import Business.WorkQueue.RescueRequest;
import Business.WorkQueue.WaterRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.Administrator.Hospital;
import ui.Utilities.GoogleMapEdit;
import ui.Utilities.GoogleMapView;
import ui.main.BaseJPanel;

/**
 *
 * @author victor
 */
public class RequestView extends BaseJPanel {

    /**
     * Creates new form NewJPanel
     */
    WorkRequest request;

    public RequestView(JPanel mainWorkArea, WorkRequest request) {
        super(mainWorkArea);
        this.request = request;
        initComponents();
        refresh();
    }

    @Override
    public void refresh() {
        jLabel4.setText(request.getLocation() == null ? "N/A" : request.getLocation());
        jLabel10.setText(request.getSender() == null ? "N/A" : request.getSender().getEmployee().getPerson().getName());
        jLabel14.setText(request.getReceiver() == null ? "N/A" : request.getReceiver().getName());
        jLabel11.setText(request.getAssignee() == null ? "N/A" : request.getAssignee().getEmployee().getPerson().getName());
        jLabel12.setText(WorkRequest.getType(request));
        jLabel13.setText(request.getResolveDate() != null ? request.getResolveDateString() : (request.getAssignDate() != null ? request.getAssignDateString() : request.getRequestDateString()));
        jLabel21.setText(request.getStatusString());
        if (request instanceof RescueRequest ) {
            jLabel24.setText("<html>" + request.getMessage() + "</html>");
        } else if (request instanceof HospitalRequest) {
            jLabel24.setText("Sent by 911");
        } else if (request instanceof CarInsuranceRequest) {
            jLabel24.setText("Evaluated Loss - " + (((CarInsuranceRequest) request).getLoss() == null ? "N/A" : ((CarInsuranceRequest) request).getLossString()));
        } else if (request instanceof HouseInsuranceRequest) {
            jLabel24.setText("Evaluated Loss - " + (((HouseInsuranceRequest) request).getLoss() == null ? "N/A" : ((HouseInsuranceRequest) request).getLossString()));
        } else if (request instanceof ElectricityRequest) {
            jLabel24.setText("Decision - " + (((ElectricityRequest) request).getDecision() == null ? "N/A" : ((ElectricityRequest) request).getDecision()));
        } else if (request instanceof WaterRequest) {
            jLabel24.setText("Decision - " + (((WaterRequest) request).getDecision() == null ? "N/A" : ((WaterRequest) request).getDecision()));
        } else if (request instanceof FoodRequest) {
            try {
                jLabel24.setText("Food Remain - " + (((FoodRequest) request).getFoodRemainString()));
            } catch (Exception ex) {
                jLabel24.setText("Food Remain - N/A");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sp = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 153, 255));

        Sp.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/house.png"))); // NOI18N
        jLabel16.setText(" Work Request:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 255));
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Sp.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Update Date:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 343, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Request Type:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 295, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("Sender:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 151, -1, -1));

        jLabel11.setText("< Email Address >");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 250, 226, -1));

        jLabel10.setText("< Name >");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 154, 226, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Receiver:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 247, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Location:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 101, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("View Request");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 25, -1, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/check.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 25, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("location");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 104, 260, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/location_48px.png"))); // NOI18N
        jLabel22.setText("View on Map");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 87, 152, 44));

        jLabel12.setText("< Email Address >");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 298, 226, -1));

        jLabel13.setText("< Email Address >");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 346, 226, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Status:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 390, -1, -1));

        jLabel21.setText("< Email Address >");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 393, 226, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Message:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 438, -1, -1));

        jLabel24.setText("< Email Address >");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 420, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Assinee:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 199, -1, -1));

        jLabel14.setText("< Email Address >");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 202, 226, -1));

        Sp.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sp, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        logoutAction();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        backAction();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        String[] locations = {request.getLocation()};
        String[] labels = {"R"};
        String[] colors = {"red"};
        nextPanel(new GoogleMapView(mainWorkArea, locations, labels, colors));
    }//GEN-LAST:event_jLabel22MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Sp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
