/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.AddressDaoImp;
import dao.CpiDao;
import dao.DliDao;
import dao.MRDao;
import dao.SaiDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Address;
import pojo.CPi;
import pojo.Dli;
import pojo.MR;
import pojo.Sai;

/**
 *
 * @author Administrator
 */
public class VALL extends javax.swing.JPanel {

    /**
     * Creates new form VALL
     */
    public VALL() {
        initComponents();
    }
      AddressDaoImp adDao;
    CpiDao cpiDao;
    DliDao dliDao;
    MRDao mrDao;
    SaiDao saiDao;
    /**
     * Creates new form VALL
     */
    public VALL(AddressDaoImp adDao,CpiDao cpiDao,DliDao dliDao,MRDao mrDao,SaiDao saiDao) {
        initComponents();
      
        this.adDao = adDao;
        this.cpiDao = cpiDao;
        this.dliDao = dliDao;
        this.mrDao = mrDao;
        this.saiDao = saiDao;
        
        showData();
    }
    
    public void showData(){
//        try{
          if(cpiDao.getCPi().size()>0){
            DefaultTableModel md1 = (DefaultTableModel) t3.getModel();
            md1.setRowCount(0);
            CPi cpi = cpiDao.getCPi().get(0);
            Object[] r1 = {cpi.getfName(),cpi.getlName(),cpi.getpNumber(),cpi.getdBirth(),cpi.getAge(),cpi.getHeight(),cpi.getWeidth(),cpi.getSsNumber()};
            md1.addRow(r1);
          }
        
         if(adDao.getAddress().size()>0){
             DefaultTableModel md2 = (DefaultTableModel) t1.getModel();
            md2.setRowCount(0);
            Address add =adDao.getAddress().get(0);
            Object[] r2 = {add.getStreet(),add.getCity(),add.getState(),add.getId()};
            md2.addRow(r2);
         }
        
        if(dliDao.getDli().size()>0){
             DefaultTableModel md3 = (DefaultTableModel) t2.getModel();
             md3.setRowCount(0);
            Dli dli = dliDao.getDli().get(0);
            Object[] r3 = new Object[5];
            r3[0] = dli.getLNumber();
            r3[1] = dli.getuDate();
            r3[2] = dli.geteDate();
            r3[3] = dli.getbType();
            r3[4] = dli.getPicture();
            md3.addRow(r3);
        }
        
        if(mrDao.getMR().size()>0){
             DefaultTableModel md4 = (DefaultTableModel) t4.getModel();
            md4.setRowCount(0);
            MR mr = mrDao.getMR().get(0);
             Object[] r4 = {mr.getMRNumber(),mr.getAg1(),mr.getAg2(),mr.getAg3()};
             md4.addRow(r4);
        }
        
       if(saiDao.getSai().size()>0){
            DefaultTableModel md5 = (DefaultTableModel) t5.getModel();
            md5.setRowCount(0);
            Sai sai = saiDao.getSai().get(0);
            Object[] r5 = {sai.getBRNumber(),sai.getANumber(),sai.getBalance(),sai.getAType()};
            md5.addRow(r5);
       }
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(this,"Please Insert Data First!!","",JOptionPane.WARNING_MESSAGE);
//        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        t5 = new javax.swing.JTable();

        jLabel6.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel6.setText("User Information System - Driver's License Information");

        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "License Number", "Date it was issued", "cityDate of expiratoin", "zipBlood Type", "pojoPicture"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                t3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(t3);
        if (t3.getColumnModel().getColumnCount() > 0) {
            t3.getColumnModel().getColumn(4).setHeaderValue("age");
        }

        jLabel7.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel7.setText("User Information System - Personal Information");

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Phone Number", "Date of Birth", "age", "Height", "Weight", "Socail Security Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                t1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(t1);
        if (t1.getColumnModel().getColumnCount() > 0) {
            t1.getColumnModel().getColumn(4).setHeaderValue("age");
            t1.getColumnModel().getColumn(5).setHeaderValue("Height");
            t1.getColumnModel().getColumn(6).setHeaderValue("Weight");
            t1.getColumnModel().getColumn(7).setResizable(false);
            t1.getColumnModel().getColumn(7).setHeaderValue("Socail Security Number");
        }

        jLabel8.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel8.setText("User Information System - Address Information");

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Street Address", "City", "State", "Zip Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                t2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(t2);

        jLabel9.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel9.setText("User Information System - Medical Record");

        t4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Medical Record Number", "Alergy1", "Alergy2", "Alergy3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                t4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(t4);

        jLabel10.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel10.setText("User Information System - Saving Account Information");

        t5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Bank Routing Number", "Bank Account Number", "Account Balance", "Account Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                t5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(t5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(230, 230, 230))
                            .addComponent(jScrollPane2)))
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_t3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_t3AncestorAdded

    private void t1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_t1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_t1AncestorAdded

    private void t2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_t2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_t2AncestorAdded

    private void t4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_t4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_t4AncestorAdded

    private void t5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_t5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_t5AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable t1;
    private javax.swing.JTable t2;
    private javax.swing.JTable t3;
    private javax.swing.JTable t4;
    private javax.swing.JTable t5;
    // End of variables declaration//GEN-END:variables
}
