/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import model.Company.CompanyDirectory;
import model.Persona.AccountDirectory;
import model.Persona.PersonDirectory;
import model.University.University;

/**
 *
 * @author aeloyq
 */
public class BaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form baseJPanel
     */
    protected JPanel mainWorkArea;
    protected University university = University.getInstance();
    protected CompanyDirectory companyDirectory = CompanyDirectory.getInstance();
    protected AccountDirectory accountDirectory = AccountDirectory.getInstance();
    protected PersonDirectory personDirectory = PersonDirectory.getInstance();

    public BaseJPanel(JPanel mainWorkArea) {
        this.mainWorkArea = mainWorkArea;
    }

    public JPanel getMainWorkArea() {
        return mainWorkArea;
    }

    public void backAction() {
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BaseJPanel bjp = (BaseJPanel) component;
        bjp.refreshTable();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.last(mainWorkArea);
    }

    public void logoutAction() {
        Component[] componentArray = mainWorkArea.getComponents();
        LoginScreen lgs = (LoginScreen) componentArray[0];
        mainWorkArea.removeAll();
        mainWorkArea.add(lgs);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.first(mainWorkArea);
    }

    public void refreshTable() {

    }

    public void nextPanel(JPanel nextJpanel) {
        mainWorkArea.add(nextJpanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }

    public void nextPanel(BaseJPanel nextJpanel) {
        nextJpanel.getMainWorkArea().add(nextJpanel);
        CardLayout layout = (CardLayout) nextJpanel.getMainWorkArea().getLayout();
        layout.next(nextJpanel.getMainWorkArea());
    }

    public void nextPanel(JPanel containerJPanel, JPanel nextJpanel) {
        containerJPanel.add(nextJpanel);
        CardLayout layout = (CardLayout) containerJPanel.getLayout();
        layout.next(containerJPanel);
    }

    public Object chooseObjectFromTable(JTable table, int column, String name) throws Exception {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose " + name + " first!");
            throw new Exception();
        }
        return table.getValueAt(selectedRow, column);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
