/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.LoginSession;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author aeloyq
 */
public class BaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form baseJPanel
     */
    protected JPanel mainWorkArea;
    protected EcoSystem system;
    protected Restaurant loginRestaurant;
    protected UserAccount loginUserAccount;
 

    public BaseJPanel() {
        this.system=LoginSession.ecoSystem;
        this.mainWorkArea = LoginSession.mainWorkArea;
        this.loginRestaurant=LoginSession.restaurant;
        this.loginUserAccount=LoginSession.userAccout;
    }

    public void backAction() {
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BaseJPanel bjp = (BaseJPanel) component;
        bjp.refreshTable();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.last(mainWorkArea);
    }

    public void logoutAction() {
        
    }
    
    public void refreshTable(){
        
    }

    public void dorefreshTable(JTable jTable,List<Object[]> rows) {
        
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        model.setRowCount(0);
        for(Object[] row:rows){
            model.addRow(row);
        }

    }
    
    public Object getChooseRowObj(JTable jTable) {
        int selectedRow = jTable.getSelectedRow();
         if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please choose  first!");
            return null;
        }
        
        return jTable.getValueAt(selectedRow, 0);
    }
    public Object getChooseRowObj(JTable jTable,int index) {
        int selectedRow = jTable.getSelectedRow();
         if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please choose  first!");
            return null;
        }
        
        return jTable.getValueAt(selectedRow, index);
    }

    public void nextPanel(JPanel nextJpanel) {
        mainWorkArea.add(nextJpanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }

    public void nextPanel(JPanel containerJPanel, JPanel nextJpanel) {
        containerJPanel.add(nextJpanel);
        CardLayout layout = (CardLayout) containerJPanel.getLayout();
        layout.next(containerJPanel);
    }

    public Object chooseObjectFromTable(JTable table, int column, String name) throws Exception {
        int selectedRow = table.getSelectedRow();
        System.out.print(selectedRow);
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose " + name + " first!");
            throw new Exception();
        }
        return table.getValueAt(selectedRow, column);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
