/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.DliDao;
import javax.swing.JOptionPane;
import pojo.Dli;

/**
 *
 * @author victor
 */
public class CJPDLI extends javax.swing.JPanel {
    DliDao dliDao;
    /**
     * Creates new form CJPDLI
     */
    public CJPDLI(DliDao dliDao) {
        initComponents();
        this.dliDao = dliDao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtPic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtLN = new javax.swing.JTextField();
        txtDiwi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDOE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        jLabel6.setText("User Information System - Driver's License Information");

        txtPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPicActionPerformed(evt);
            }
        });

        jLabel7.setText("Picture:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNActionPerformed(evt);
            }
        });

        txtDiwi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiwiActionPerformed(evt);
            }
        });

        jLabel2.setText("License Number:");

        txtDOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOEActionPerformed(evt);
            }
        });

        jLabel3.setText("Date it was issued:");

        txtBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of expiration:");

        jLabel5.setText("Blood Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                            .addComponent(txtDOE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiwi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPic)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiwi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSave)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPicActionPerformed

    private void txtLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNActionPerformed

    private void txtDiwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiwiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiwiActionPerformed

    private void txtDOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOEActionPerformed

    private void txtBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBTActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
     
        int LNumber=0;
        String uDate ="";
        String eDate = "";
        String bType="";
        String pictrue="";
       try{
        LNumber = Integer.parseInt(txtLN.getText());
        uDate = txtDiwi.getText();
        eDate = txtDOE.getText();
        bType = txtBT.getText();
        pictrue = txtPic.getText();
       }catch(Exception e){
             JOptionPane.showMessageDialog(this,"Please check the input format","",JOptionPane.WARNING_MESSAGE);
       }
        
          
        Dli dli = dliDao.addDli();
        
        dli.setLNumber(LNumber);
        dli.setuDate(uDate);
        dli.seteDate(eDate);
        dli.setbType(bType);
        dli.setPicture(pictrue);

        JOptionPane.showMessageDialog(this,"Add Succeed!");
        
        txtLN.setText("");
        txtDiwi.setText("");
        txtDOE.setText("");
        txtBT.setText("");
        txtPic.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBT;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDiwi;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtPic;
    // End of variables declaration//GEN-END:variables
}
